### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by Alexmelman88** [vinceliuice/Fluent-icon-theme#26]
Hi, I really like your icon pack, but there are a couple of unpleasant things, there is no icon for Poedit application (net.poedit.Poedit.svg), you can make a symlink to lokalize.svg, and the Drawing application icon (com.github.maoschanz.drawing.svg) looks strange in relation to other icons, no blur and transparency. It would be nice to do something about it. Thank you!

**Comment by vinceliuice** [comment]
No problem!
