### ISSUE TITLE
能不能适配下jetbrain旗下的app的icon，比如idea , pycharm , android studio

### ISSUE THREAD

**Issue by nocteowl** [vinceliuice/Fluent-icon-theme#48]
用Linux的大部分都是开发人员，如果能适配就非常棒，另外，开放一个打赏渠道吧，虽然开源免费

**Comment by vinceliuice** [comment]
jetbrain 的好多图标都是用自己的图标不用第三方主题的，虽然我做了他们的图标不过你需要自己修改启动器里的图标id（路径）才行
