### ISSUE TITLE
[Icon Request] AnyType

### ISSUE THREAD

**Issue by jackgraddon** [vinceliuice/Fluent-icon-theme#52]
**Tell me things about the app or icon**
1. App name: AnyType
2. App Webside: https://anytype.io
3. App icon name: anytype

**Additional context**
This is what the default icon looks like on iOS, macOS, and Windows. When installing onto Linux (at least in my experience) the icon is a generic application icon (the file with a gear for this icon theme)
![image](https://github.com/vinceliuice/Fluent-icon-theme/assets/61634132/f9612170-18e3-4e20-898b-c95efe2fd9b0)

**Comment by jackgraddon** [comment]
Here are some I made, if you want to use them you have full permission, but if you wish to make your own go for it :)
[AnyType.zip](https://github.com/vinceliuice/Fluent-icon-theme/files/12907886/AnyType.zip) (Contains .svg, .png, and .icns files for a light and dark version of the AnyType app icon)

**Comment by vinceliuice** [comment]
Fixed
