### ISSUE TITLE
Wrong Clipboard Icon after Plasma 6 Update

### ISSUE THREAD

**Issue by noir-Z** [vinceliuice/Fluent-icon-theme#60]
**Describe the bug**
Clipboard Icon in Tray changed to inconsistent style after updating to Plasma 6

**To Reproduce**
1. Use Plasma 6
2. Apply Fluent Icon theme
3. (Presumably) wrong clipboard icon shows up in the system tray

**Expected behavior**
Consistent style with the other tray icons

**Screenshots**
![image](https://github.com/vinceliuice/Fluent-icon-theme/assets/45096516/189af001-6959-41ae-8691-e23e2ad6df05)

**Desktop (please complete the following information):**
 - OS: Arch Linux (6.7.8-arch1-1)
 - Plasma Version : 6.0.1
 - Fluent Icon Theme installed through KDE's Discover

**Comment by moodyhunter** [comment]
Plasma 6 has changed the name of icons to use, possible related: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3595

**Comment by vinceliuice** [comment]
Fixed now

**Comment by noir-Z** [comment]
Thank you so much for your work, these are the best icons!
