### ISSUE TITLE
invalid icon Documents folder

### ISSUE THREAD

**Issue by holiq** [vinceliuice/Fluent-icon-theme#63]
**Describe the bug**
Invalid icon on Documents folder

**Screenshots**
![Screenshot from 2024-05-04 10-23-07](https://github.com/vinceliuice/Fluent-icon-theme/assets/30729921/db571903-bf84-4ef8-b699-0db5a9567344)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - App Nautilus
 - Version 24.04 LTS

**Comment by hologerry** [comment]
same issue
