### ISSUE TITLE
[Icon request] Notifications - Missing icon what been copied

### ISSUE THREAD

**Issue by niri-san** [vinceliuice/Fluent-icon-theme#75]
KDE Plasma 6 - Notifications

If we copy/paste files, on the notification tray we see a missing icon of what been copied.

![Screenshot_20240619_112838](https://github.com/vinceliuice/Fluent-icon-theme/assets/160327855/81c1b946-0f63-4842-9a4e-66f44f07076a)

Details
```
Operating System: openSUSE Tumbleweed 20240617
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Graphics Platform: Wayland
```

**Comment by vinceliuice** [comment]
This is svg mimetype icon

**Comment by niri-san** [comment]
It should be like that? If so, this issue should be closed as completed. Thank you.

**Comment by niri-san** [comment]
This issue is closed as it is incomplete and submitted incorrectly.
