### ISSUE TITLE
[Icon changes] KDE Plasma 6 - Application Menu/Launcher - Kate

### ISSUE THREAD

**Issue by niri-san** [vinceliuice/Fluent-icon-theme#77]
From KDE Plasma 6 - Application Menu/Launcher

Development / Kate
Utilities / Kate

Kate shown as a symbolic on both Application Menu/Launcher instead of a colored icon.
![Screenshot_20240619_155943](https://github.com/vinceliuice/Fluent-icon-theme/assets/160327855/5b7fc110-01cb-4aec-8492-a36a1a6bfadd)

![Screenshot_20240619_160742](https://github.com/vinceliuice/Fluent-icon-theme/assets/160327855/35cdc576-5fa4-4776-86f6-358ce5b6d72d)

Details
```
Operating System: openSUSE Tumbleweed 20240617
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Graphics Platform: Wayland
```

**Comment by vinceliuice** [comment]
Fixed
